nom : Rapport de bug
description : Déposez un rapport de bug concernant le firmware.
étiquettes : ["bug"]
corps:
   - tapez : démarque
     les attributs:
       valeur : |
         Merci d'avoir pris le temps de remplir un problème, ce modèle est destiné à tout problème lié au firmware Kali Zero.
   - tapez : zone de texte
     identifiant : description
     les attributs:
       label : Décrivez le bug.
       description: "Une description claire et concise de la nature du bug."
     validations :
       obligatoire : vrai
   - tapez : zone de texte
     identifiant : repro
     les attributs:
       Étiquette : Reproduction
       description : "Comment ce bug peut-il être reproduit ?"
       espace réservé : |
         1. Allumez...
         2. Appuyez sur le bouton '....'
         3. Attendez la phase de lune
         4. Ça brûle
     validations :
       obligatoire : vrai
   - tapez : entrée
     identifiant : cible
     les attributs:
       étiquette : cible
       description : Spécifiez la cible
       # Target semble être largement ignoré par les sources extérieures.
   - tapez : zone de texte
     identifiant : journaux
     les attributs:
       étiquette : Journaux
       description : Joignez vos journaux de débogage ici
       rendu : texte
       # Évitez le rendu en Markdown ici.
   - tapez : zone de texte
     identifiant : autre chose
     les attributs:
       étiquette : Autre chose ?
       description : Faites-nous savoir si vous avez autre chose à partager.