nom : Améliorations
description : Suggérer des améliorations pour toute fonctionnalité existante dans le micrologiciel.
corps:
   - tapez : démarque
     les attributs:
       valeur : |
         Merci d'avoir pris le temps de répondre à un problème. Ce modèle est destiné aux demandes de fonctionnalités et aux améliorations des fonctionnalités déjà existantes.
   - tapez : zone de texte
     identifiant : proposition
     les attributs:
       label : "Décrivez l'amélioration que vous proposez."
       descriptif : |
         N'hésitez pas à décrire avec autant de détails que vous le souhaitez.
     validations :
       obligatoire : vrai
   - tapez : zone de texte
     identifiant : autre chose
     les attributs:
       étiquette : Autre chose ?
       description : Faites-nous savoir si vous avez autre chose à partager.