name: "FAP: Build for multiple SDK sources"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Official Dev channel
            sdk-channel: dev
          - name: Official Release channel
            sdk-channel: release
          - name: Unleashed Dev
            sdk-index-url: https://up.unleashedflip.com/directory.json
            sdk-channel: dev
          - name: Unleashed Release
            sdk-index-url: https://up.unleashedflip.com/directory.json
            sdk-channel: release
    name: 'ufbt: Build for ${{ matrix.name }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.0
        id: build-app
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
          sdk-index-url: ${{ matrix.sdk-index-url }}
      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}