name: 'Lint'

on:
  push:
    branches:
      - dev
      - main
    tags:
      - '*'
  pull_request:

env:
  SET_GH_OUTPUT: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Check code formatting'
        run: ./fbt lint lint_py
