name: 'Webhook'

on:
  push:
  # pull_request:
  #   types:
  #     - "opened"
  #     - "closed"
  #     - "reopened"
  release:
    types:
      - "published"
  workflow_run:
    workflows:
      - "Build"
      - "Hotfix"
      - "Lint"
      - "Release"
      - "SonarCloud"
      - "Submodules"
    types:
      - "completed"
  issues:
    types:
      - "opened"
      - "closed"
      - "reopened"
  issue_comment:
    types:
      - "created"

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: Send webhook
        env:
          BUILD_WEBHOOK: ${{ secrets.BUILD_WEBHOOK }}
          DEV_WEBHOOK: ${{ secrets.DEV_WEBHOOK }}
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: python .github/workflow_data/webhook.py
